name: adminglobalcare
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  loading_animation_widget: ^1.3.0
  pluto_grid: ^8.0.0
  supabase_flutter: ^2.8.3
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ # Include any additional assets if needed
