name: hospital
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.2
  image_picker: ^1.1.2
  curved_navigation_bar: ^1.0.3
  audioplayers: ^6.1.0 
  loading_animation_widget: ^1.3.0
  image_picker_web: ^4.0.0
  local_auth: ^2.3.0
  flutter_tts: ^4.2.1
  vibration:  ^3.0.0
  fl_chart:  ^0.70.2
  file_picker: ^8.1.7
  permission_handler: ^11.3.1
  dio: ^5.8.0+1
  path_provider: ^2.1.5
  open_file: ^3.5.10
  animate_do: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/
